#!/usr/bin/env bash
# check-codecs.sh — Verify or regenerate auto-generated codecs.
#
# Usage:
#   ./check-codecs.sh              # Check that src/Codecs.elm matches auto-generated output (CI mode)
#   ./check-codecs.sh --regenerate # Regenerate src/Codecs.elm from the stub
#
# The codecs in src/Codecs.elm are generated by elm-review-derive from
# src/Codecs.elm.stub. Two manual adjustments are applied automatically:
#   1. Lamdera.SessionId is opaque, so sessionIdCodec is replaced with Codec.string
#   2. Amount has a phantom type parameter, so amountCodec is provided in the stub

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

STUB="src/Codecs.elm.stub"
TARGET="src/Codecs.elm"

generate() {
    cp "$STUB" "$TARGET"

    # Run elm-review-derive to fill in Debug.todo stubs
    echo "Y" | elm-review --fix-all \
        --compiler lamdera \
        --template gampleman/elm-review-derive/preview \
        2>&1 || true

    # Post-process: replace sessionIdCodec reference with Codec.string
    sed -i 's/(Codec.set sessionIdCodec)/(Codec.set Codec.string)/g' "$TARGET"

    # Post-process: remove the generated sessionIdCodec definition and import Lamdera
    sed -i '/^import Lamdera$/d' "$TARGET"
    # Remove the sessionIdCodec block (type annotation + definition + Debug.todo + error message + blank lines)
    sed -i '/^sessionIdCodec/,/^$/d' "$TARGET"

    # Format the result
    elm-format "$TARGET" --yes
}

if [ "${1:-}" = "--regenerate" ]; then
    generate
    echo "✅ src/Codecs.elm regenerated."
    exit 0
fi

# CI check mode: generate into a temp file and compare
BACKUP=$(mktemp)
cp "$TARGET" "$BACKUP"

generate > /dev/null 2>&1

if diff -u "$BACKUP" "$TARGET" > /dev/null 2>&1; then
    # Restore the original (identical) file
    cp "$BACKUP" "$TARGET"
    rm "$BACKUP"
    echo "✅ Codecs are up to date."
    exit 0
else
    echo "❌ src/Codecs.elm is out of date with the auto-generated output."
    echo ""
    echo "Diff (committed vs generated):"
    diff -u "$BACKUP" "$TARGET" || true
    # Restore the original file
    cp "$BACKUP" "$TARGET"
    rm "$BACKUP"
    echo ""
    echo "Run './check-codecs.sh --regenerate' to update."
    exit 1
fi
