module Evergreen.Migrate.V11 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V11.Types
import Evergreen.V8.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V8.Types.FrontendModel -> ModelMigration Evergreen.V11.Types.FrontendModel Evergreen.V11.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V8.Types.BackendModel -> ModelMigration Evergreen.V11.Types.BackendModel Evergreen.V11.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V8.Types.FrontendMsg -> MsgMigration Evergreen.V11.Types.FrontendMsg Evergreen.V11.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V8.Types.ToBackend -> MsgMigration Evergreen.V11.Types.ToBackend Evergreen.V11.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V8.Types.BackendMsg -> MsgMigration Evergreen.V11.Types.BackendMsg Evergreen.V11.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V8.Types.ToFrontend -> MsgMigration Evergreen.V11.Types.ToFrontend Evergreen.V11.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V8.Types.FrontendModel -> Evergreen.V11.Types.FrontendModel
migrate_Types_FrontendModel old =
    { page = old.page |> migrate_Types_Page
    , showDialog = old.showDialog |> Maybe.map migrate_Types_Dialog
    , user = old.user
    , nameValidity = old.nameValidity |> migrate_Types_NameValidity
    , userGroups =
        old.userGroups
            |> Maybe.map
                (\rec ->
                    { debitors = rec.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    , creditors = rec.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    }
                )
    , group = old.group
    , groupValidity = old.groupValidity |> migrate_Types_NameValidity
    , groupTransactions =
        old.groupTransactions
            |> List.map
                (\rec ->
                    { description = rec.description
                    , year = rec.year
                    , month = rec.month
                    , day = rec.day
                    , total = rec.total |> migrate_Types_Amount
                    , share = rec.share |> migrate_Types_Amount
                    }
                )
    , key = old.key
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    }


migrate_Types_AddGroupDialogModel : Evergreen.V8.Types.AddGroupDialogModel -> Evergreen.V11.Types.AddGroupDialogModel
migrate_Types_AddGroupDialogModel old =
    { name = old.name
    , nameInvalid = old.nameInvalid
    , members = old.members |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , submitted = old.submitted
    }


migrate_Types_AddPersonDialogModel : Evergreen.V8.Types.AddPersonDialogModel -> Evergreen.V11.Types.AddPersonDialogModel
migrate_Types_AddPersonDialogModel old =
    old


migrate_Types_AddSpendingDialogModel : Evergreen.V8.Types.AddSpendingDialogModel -> Evergreen.V11.Types.AddSpendingDialogModel
migrate_Types_AddSpendingDialogModel old =
    { description = old.description
    , date = old.date
    , dateText = old.dateText
    , datePickerModel = old.datePickerModel
    , total = old.total
    , credits = old.credits |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , debits = old.debits |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , submitted = old.submitted
    }


migrate_Types_Amount : Evergreen.V8.Types.Amount a_old -> Evergreen.V11.Types.Amount a_new
migrate_Types_Amount old =
    case old of
        Evergreen.V8.Types.Amount p0 ->
            Evergreen.V11.Types.Amount p0


migrate_Types_Dialog : Evergreen.V8.Types.Dialog -> Evergreen.V11.Types.Dialog
migrate_Types_Dialog old =
    case old of
        Evergreen.V8.Types.AddPersonDialog p0 ->
            Evergreen.V11.Types.AddPersonDialog (p0 |> migrate_Types_AddPersonDialogModel)

        Evergreen.V8.Types.AddGroupDialog p0 ->
            Evergreen.V11.Types.AddGroupDialog (p0 |> migrate_Types_AddGroupDialogModel)

        Evergreen.V8.Types.AddSpendingDialog p0 ->
            Evergreen.V11.Types.AddSpendingDialog (p0 |> migrate_Types_AddSpendingDialogModel)

        Evergreen.V8.Types.PasswordDialog p0 ->
            Evergreen.V11.Types.PasswordDialog (p0 |> migrate_Types_PasswordDialogModel)


migrate_Types_Group : Evergreen.V8.Types.Group -> Evergreen.V11.Types.Group
migrate_Types_Group old =
    old |> Dict.map (\k -> migrate_Types_Share)


migrate_Types_NameValidity : Evergreen.V8.Types.NameValidity -> Evergreen.V11.Types.NameValidity
migrate_Types_NameValidity old =
    case old of
        Evergreen.V8.Types.Complete ->
            Evergreen.V11.Types.Complete

        Evergreen.V8.Types.Incomplete ->
            Evergreen.V11.Types.Incomplete

        Evergreen.V8.Types.InvalidPrefix ->
            Evergreen.V11.Types.InvalidPrefix


migrate_Types_Page : Evergreen.V8.Types.Page -> Evergreen.V11.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V8.Types.Home ->
            Evergreen.V11.Types.Home

        Evergreen.V8.Types.NotFound ->
            Evergreen.V11.Types.NotFound


migrate_Types_PasswordDialogModel : Evergreen.V8.Types.PasswordDialogModel -> Evergreen.V11.Types.PasswordDialogModel
migrate_Types_PasswordDialogModel old =
    old


migrate_Types_Share : Evergreen.V8.Types.Share -> Evergreen.V11.Types.Share
migrate_Types_Share old =
    case old of
        Evergreen.V8.Types.Share p0 ->
            Evergreen.V11.Types.Share p0


migrate_Types_ToBackend : Evergreen.V8.Types.ToBackend -> Evergreen.V11.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V8.Types.NoOpToBackend ->
            Evergreen.V11.Types.NoOpToBackend

        Evergreen.V8.Types.CheckValidName p0 ->
            Evergreen.V11.Types.CheckValidName p0

        Evergreen.V8.Types.AutocompletePerson p0 ->
            Evergreen.V11.Types.AutocompletePerson p0

        Evergreen.V8.Types.AutocompleteGroup p0 ->
            Evergreen.V11.Types.AutocompleteGroup p0

        Evergreen.V8.Types.CreatePerson p0 ->
            Evergreen.V11.Types.CreatePerson p0

        Evergreen.V8.Types.CreateGroup p0 p1 ->
            Evergreen.V11.Types.CreateGroup p0 (p1 |> Dict.map (\k -> migrate_Types_Share))

        Evergreen.V8.Types.CreateSpending p0 ->
            Evergreen.V11.Types.CreateSpending
                { description = p0.description
                , year = p0.year
                , month = p0.month
                , day = p0.day
                , total = p0.total |> migrate_Types_Amount
                , credits = p0.credits |> Dict.map (\k -> migrate_Types_Amount)
                , debits = p0.debits |> Dict.map (\k -> migrate_Types_Amount)
                }

        Evergreen.V8.Types.RequestUserGroups p0 ->
            Evergreen.V11.Types.RequestUserGroups p0

        Evergreen.V8.Types.RequestGroupTransactions p0 ->
            Evergreen.V11.Types.RequestGroupTransactions p0

        Evergreen.V8.Types.CheckPassword p0 ->
            Evergreen.V11.Types.CheckPassword p0


migrate_Types_ToFrontend : Evergreen.V8.Types.ToFrontend -> Evergreen.V11.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V8.Types.NoOpToFrontend ->
            Evergreen.V11.Types.NoOpToFrontend

        Evergreen.V8.Types.OperationSuccessful ->
            Evergreen.V11.Types.OperationSuccessful

        Evergreen.V8.Types.NameAlreadyExists p0 ->
            Evergreen.V11.Types.NameAlreadyExists p0

        Evergreen.V8.Types.InvalidPersonPrefix p0 ->
            Evergreen.V11.Types.InvalidPersonPrefix p0

        Evergreen.V8.Types.AutocompletePersonPrefix p0 ->
            Evergreen.V11.Types.AutocompletePersonPrefix
                { prefixLower = p0.prefix
                , longestCommonPrefix = p0.longestCommonPrefix
                , complete = p0.complete
                }

        Evergreen.V8.Types.InvalidGroupPrefix p0 ->
            Evergreen.V11.Types.InvalidGroupPrefix p0

        Evergreen.V8.Types.AutocompleteGroupPrefix p0 ->
            Evergreen.V11.Types.AutocompleteGroupPrefix
                { prefixLower = p0.prefix
                , longestCommonPrefix = p0.longestCommonPrefix
                , complete = p0.complete
                }

        Evergreen.V8.Types.ListUserGroups p0 ->
            Evergreen.V11.Types.ListUserGroups
                { user = p0.user
                , debitors = p0.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                , creditors = p0.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                }

        Evergreen.V8.Types.ListGroupTransactions p0 ->
            Evergreen.V11.Types.ListGroupTransactions
                { group = p0.group
                , transactions =
                    p0.transactions
                        |> List.map
                            (\rec1 ->
                                { description = rec1.description
                                , year = rec1.year
                                , month = rec1.month
                                , day = rec1.day
                                , total = rec1.total |> migrate_Types_Amount
                                , share = rec1.share |> migrate_Types_Amount
                                }
                            )
                }
