module Evergreen.Migrate.V26 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V24.Types
import Evergreen.V26.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V24.Types.FrontendModel -> ModelMigration Evergreen.V26.Types.FrontendModel Evergreen.V26.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V24.Types.BackendModel -> ModelMigration Evergreen.V26.Types.BackendModel Evergreen.V26.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V24.Types.FrontendMsg -> MsgMigration Evergreen.V26.Types.FrontendMsg Evergreen.V26.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V24.Types.ToBackend -> MsgMigration Evergreen.V26.Types.ToBackend Evergreen.V26.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V24.Types.BackendMsg -> MsgMigration Evergreen.V26.Types.BackendMsg Evergreen.V26.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V24.Types.ToFrontend -> MsgMigration Evergreen.V26.Types.ToFrontend Evergreen.V26.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V24.Types.BackendModel -> Evergreen.V26.Types.BackendModel
migrate_Types_BackendModel old =
    { years = old.years |> Dict.map (\k -> migrate_Types_Year)
    , spendings = (Unimplemented {- Type `Array (Evergreen.V26.Types.Spending)` was added in V26. I need you to set a default value. -})
    , groups = old.groups |> Dict.map (\k -> migrate_Types_Group)
    , totalGroupCredits = old.totalGroupCredits |> Dict.map (\k -> Dict.map (\k -> migrate_Types_Amount))
    , persons = old.persons
    , nextPersonId = old.nextPersonId
    , loggedInSessions = old.loggedInSessions
    }


migrate_Types_FrontendModel : Evergreen.V24.Types.FrontendModel -> Evergreen.V26.Types.FrontendModel
migrate_Types_FrontendModel old =
    { page = old.page |> migrate_Types_Page
    , showDialog = old.showDialog |> Maybe.map migrate_Types_Dialog
    , errorMessage = (Unimplemented {- Type `Maybe (String)` was added in V26. I need you to set a default value. -})
    , user = old.user
    , nameValidity = old.nameValidity |> migrate_Types_NameValidity
    , userGroups =
        old.userGroups
            |> Maybe.map
                (\rec ->
                    { debitors = rec.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    , creditors = rec.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    }
                )
    , group = old.group
    , groupValidity = old.groupValidity |> migrate_Types_NameValidity
    , groupTransactions =
        old.groupTransactions
            |> List.map
                (\rec ->
                    { transactionId = rec.transactionId |> migrate_Types_TransactionId
                    , spendingId = (Unimplemented {- Type `Evergreen.V26.Types.SpendingId` was added in V26. I need you to set a default value. -})
                    , description = rec.description
                    , year = rec.year
                    , month = rec.month
                    , day = rec.day
                    , total = rec.total |> migrate_Types_Amount
                    , share = rec.share |> migrate_Types_Amount
                    }
                )
    , key = old.key
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , checkingAuthentication = old.checkingAuthentication
    , theme = old.theme |> migrate_Types_Theme
    }


migrate_Types_AddGroupDialogModel : Evergreen.V24.Types.AddGroupDialogModel -> Evergreen.V26.Types.AddGroupDialogModel
migrate_Types_AddGroupDialogModel old =
    { name = old.name
    , nameInvalid = old.nameInvalid
    , members = old.members |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , submitted = old.submitted
    }


migrate_Types_AddPersonDialogModel : Evergreen.V24.Types.AddPersonDialogModel -> Evergreen.V26.Types.AddPersonDialogModel
migrate_Types_AddPersonDialogModel old =
    old


migrate_Types_AddSpendingDialogModel : Evergreen.V24.Types.AddSpendingDialogModel -> Evergreen.V26.Types.AddSpendingDialogModel
migrate_Types_AddSpendingDialogModel old =
    { spendingId = (Unimplemented {- Type `Maybe (Evergreen.V26.Types.SpendingId)` was added in V26. I need you to set a default value. -})
    , description = old.description
    , total = old.total
    , date = old.date
    , today = (Unimplemented {- Type `Maybe (justinmimbs/date:Date.Date)` was added in V26. I need you to set a default value. -})
    , dateText = old.dateText
    , datePickerModel = old.datePickerModel
    , credits = old.credits |> List.map (Unimplemented {- Type changed from `(String, String, Evergreen.V24.Types.NameValidity)` to `Evergreen.V26.Types.TransactionLine`. I need you to write this migration. -})
    , debits = old.debits |> List.map (Unimplemented {- Type changed from `(String, String, Evergreen.V24.Types.NameValidity)` to `Evergreen.V26.Types.TransactionLine`. I need you to write this migration. -})
    , submitted = old.submitted
    , transactionId = (Unimplemented {- Field of type `Maybe (Evergreen.V24.Types.TransactionId)` was removed in V26. I need you to do something with the `old.transactionId` value if you wish to keep the data, then remove this line. -})
    }


migrate_Types_Amount : Evergreen.V24.Types.Amount a_old -> Evergreen.V26.Types.Amount a_new
migrate_Types_Amount old =
    case old of
        Evergreen.V24.Types.Amount p0 ->
            Evergreen.V26.Types.Amount p0


migrate_Types_Day : Evergreen.V24.Types.Day -> Evergreen.V26.Types.Day
migrate_Types_Day old =
    { transactions = (Unimplemented {- Type `Array (Evergreen.V26.Types.Transaction)` was added in V26. I need you to set a default value. -})
    , totalGroupCredits = old.totalGroupCredits |> Dict.map (\k -> Dict.map (\k -> migrate_Types_Amount))
    , spendings = (Unimplemented {- Field of type `List (Evergreen.V24.Types.Spending)` was removed in V26. I need you to do something with the `old.spendings` value if you wish to keep the data, then remove this line. -})
    }


migrate_Types_Dialog : Evergreen.V24.Types.Dialog -> Evergreen.V26.Types.Dialog
migrate_Types_Dialog old =
    case old of
        Evergreen.V24.Types.AddPersonDialog p0 ->
            Evergreen.V26.Types.AddPersonDialog (p0 |> migrate_Types_AddPersonDialogModel)

        Evergreen.V24.Types.AddGroupDialog p0 ->
            Evergreen.V26.Types.AddGroupDialog (p0 |> migrate_Types_AddGroupDialogModel)

        Evergreen.V24.Types.AddSpendingDialog p0 ->
            Evergreen.V26.Types.AddSpendingDialog (p0 |> migrate_Types_AddSpendingDialogModel)

        Evergreen.V24.Types.ConfirmDeleteDialog p0 ->
            Evergreen.V26.Types.ConfirmDeleteDialog (p0 |> migrate_Types_SpendingId)

        Evergreen.V24.Types.PasswordDialog p0 ->
            Evergreen.V26.Types.PasswordDialog (p0 |> migrate_Types_PasswordDialogModel)


migrate_Types_FrontendMsg : Evergreen.V24.Types.FrontendMsg -> Evergreen.V26.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V24.Types.UrlClicked p0 ->
            Evergreen.V26.Types.UrlClicked p0

        Evergreen.V24.Types.UrlChanged p0 ->
            Evergreen.V26.Types.UrlChanged p0

        Evergreen.V24.Types.NoOpFrontendMsg ->
            Evergreen.V26.Types.NoOpFrontendMsg

        Evergreen.V24.Types.ShowAddPersonDialog ->
            Evergreen.V26.Types.ShowAddPersonDialog

        Evergreen.V24.Types.ShowAddGroupDialog ->
            Evergreen.V26.Types.ShowAddGroupDialog

        Evergreen.V24.Types.ShowAddSpendingDialog p0 ->
            Evergreen.V26.Types.ShowAddSpendingDialog (p0 |> Maybe.map migrate_Types_SpendingReference)

        Evergreen.V24.Types.ShowConfirmDeleteDialog p0 ->
            Evergreen.V26.Types.ShowConfirmDeleteDialog (p0 |> migrate_Types_SpendingId)

        Evergreen.V24.Types.ConfirmDeleteTransaction p0 ->
            (Unimplemented
             {- `ConfirmDeleteTransaction` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.ConfirmDeleteTransaction value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.SetToday p0 ->
            Evergreen.V26.Types.SetToday p0

        Evergreen.V24.Types.Submit ->
            Evergreen.V26.Types.Submit

        Evergreen.V24.Types.Cancel ->
            Evergreen.V26.Types.Cancel

        Evergreen.V24.Types.UpdateName p0 ->
            Evergreen.V26.Types.UpdateName p0

        Evergreen.V24.Types.AddMember p0 ->
            Evergreen.V26.Types.AddMember p0

        Evergreen.V24.Types.UpdateMember p0 p1 ->
            Evergreen.V26.Types.UpdateMember p0 p1

        Evergreen.V24.Types.UpdateShare p0 p1 ->
            Evergreen.V26.Types.UpdateShare p0 p1

        Evergreen.V24.Types.ChangeDatePicker p0 ->
            (Unimplemented
             {- `ChangeDatePicker` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.ChangeDatePicker value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.UpdateTotal p0 ->
            (Unimplemented
             {- `UpdateTotal` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.UpdateTotal value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.AddCreditor p0 ->
            Evergreen.V26.Types.AddCreditor p0

        Evergreen.V24.Types.UpdateCreditor p0 p1 ->
            (Unimplemented
             {- `UpdateCreditor` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.UpdateCreditor value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.UpdateCredit p0 p1 ->
            (Unimplemented
             {- `UpdateCredit` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.UpdateCredit value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.AddDebitor p0 ->
            Evergreen.V26.Types.AddDebitor p0

        Evergreen.V24.Types.UpdateDebitor p0 p1 ->
            (Unimplemented
             {- `UpdateDebitor` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.UpdateDebitor value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.UpdateDebit p0 p1 ->
            (Unimplemented
             {- `UpdateDebit` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.UpdateDebit value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.UpdateGroupName p0 ->
            Evergreen.V26.Types.UpdateGroupName p0

        Evergreen.V24.Types.UpdatePassword p0 ->
            Evergreen.V26.Types.UpdatePassword p0

        Evergreen.V24.Types.UpdateJson p0 ->
            Evergreen.V26.Types.UpdateJson p0

        Evergreen.V24.Types.ViewportChanged p0 p1 ->
            Evergreen.V26.Types.ViewportChanged p0 p1

        Evergreen.V24.Types.ToggleTheme ->
            Evergreen.V26.Types.ToggleTheme

        notices ->
            {- @NOTICE `ConfirmDeleteSpending Evergreen.V26.Types.SpendingId` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateSpendingDate fabhof/elm-ui-datepicker:DatePicker.ChangeEvent` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateSpendingTotal String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `RemoveCredit Int` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `ToggleCreditDetails Int` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateCreditDate Int fabhof/elm-ui-datepicker:DatePicker.ChangeEvent` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateCreditSecondaryDescription Int String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateCreditGroup Int String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateCreditAmount Int String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `RemoveDebit Int` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `ToggleDebitDetails Int` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateDebitDate Int fabhof/elm-ui-datepicker:DatePicker.ChangeEvent` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateDebitSecondaryDescription Int String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateDebitGroup Int String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateDebitAmount Int String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_Group : Evergreen.V24.Types.Group -> Evergreen.V26.Types.Group
migrate_Types_Group old =
    old |> Dict.map (\k -> migrate_Types_Share)


migrate_Types_Month : Evergreen.V24.Types.Month -> Evergreen.V26.Types.Month
migrate_Types_Month old =
    { days = old.days |> Dict.map (\k -> migrate_Types_Day)
    , totalGroupCredits = old.totalGroupCredits |> Dict.map (\k -> Dict.map (\k -> migrate_Types_Amount))
    }


migrate_Types_NameValidity : Evergreen.V24.Types.NameValidity -> Evergreen.V26.Types.NameValidity
migrate_Types_NameValidity old =
    case old of
        Evergreen.V24.Types.Complete ->
            Evergreen.V26.Types.Complete

        Evergreen.V24.Types.Incomplete ->
            Evergreen.V26.Types.Incomplete

        Evergreen.V24.Types.InvalidPrefix ->
            Evergreen.V26.Types.InvalidPrefix


migrate_Types_Page : Evergreen.V24.Types.Page -> Evergreen.V26.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V24.Types.Home ->
            Evergreen.V26.Types.Home

        Evergreen.V24.Types.Json p0 ->
            Evergreen.V26.Types.Json p0

        Evergreen.V24.Types.Import p0 ->
            Evergreen.V26.Types.Import p0

        Evergreen.V24.Types.NotFound ->
            Evergreen.V26.Types.NotFound


migrate_Types_PasswordDialogModel : Evergreen.V24.Types.PasswordDialogModel -> Evergreen.V26.Types.PasswordDialogModel
migrate_Types_PasswordDialogModel old =
    old


migrate_Types_Share : Evergreen.V24.Types.Share -> Evergreen.V26.Types.Share
migrate_Types_Share old =
    case old of
        Evergreen.V24.Types.Share p0 ->
            Evergreen.V26.Types.Share p0


migrate_Types_SpendingId : Evergreen.V24.Types.TransactionId -> Evergreen.V26.Types.SpendingId
migrate_Types_SpendingId old =
    old |> (Unimplemented {- Type changed from `{}` to `Int`. I need you to write this migration. -})


migrate_Types_SpendingReference : Evergreen.V24.Types.TransactionId -> Evergreen.V26.Types.SpendingReference
migrate_Types_SpendingReference old =
    { spendingId = (Unimplemented {- Type `Evergreen.V26.Types.SpendingId` was added in V26. I need you to set a default value. -})
    , transactionId = (Unimplemented {- Type `Evergreen.V26.Types.TransactionId` was added in V26. I need you to set a default value. -})
    , day = (Unimplemented {- Field of type `Int` was removed in V26. I need you to do something with the `old.day` value if you wish to keep the data, then remove this line. -})
    , index = (Unimplemented {- Field of type `Int` was removed in V26. I need you to do something with the `old.index` value if you wish to keep the data, then remove this line. -})
    , month = (Unimplemented {- Field of type `Int` was removed in V26. I need you to do something with the `old.month` value if you wish to keep the data, then remove this line. -})
    , year = (Unimplemented {- Field of type `Int` was removed in V26. I need you to do something with the `old.year` value if you wish to keep the data, then remove this line. -})
    }


migrate_Types_Theme : Evergreen.V24.Types.Theme -> Evergreen.V26.Types.Theme
migrate_Types_Theme old =
    case old of
        Evergreen.V24.Types.LightMode ->
            Evergreen.V26.Types.LightMode

        Evergreen.V24.Types.DarkMode ->
            Evergreen.V26.Types.DarkMode


migrate_Types_ToBackend : Evergreen.V24.Types.ToBackend -> Evergreen.V26.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V24.Types.NoOpToBackend ->
            Evergreen.V26.Types.NoOpToBackend

        Evergreen.V24.Types.CheckValidName p0 ->
            Evergreen.V26.Types.CheckValidName p0

        Evergreen.V24.Types.AutocompletePerson p0 ->
            Evergreen.V26.Types.AutocompletePerson p0

        Evergreen.V24.Types.AutocompleteGroup p0 ->
            Evergreen.V26.Types.AutocompleteGroup p0

        Evergreen.V24.Types.CreatePerson p0 ->
            Evergreen.V26.Types.CreatePerson p0

        Evergreen.V24.Types.CreateGroup p0 p1 ->
            Evergreen.V26.Types.CreateGroup p0 (p1 |> Dict.map (\k -> migrate_Types_Share))

        Evergreen.V24.Types.CreateSpending p0 ->
            Evergreen.V26.Types.CreateSpending
                { description = p0.description
                , total = p0.total |> migrate_Types_Amount
                , transactions = (Unimplemented {- Type `List (Evergreen.V26.Types.SpendingTransaction)` was added in V26. I need you to set a default value. -})
                , credits = (Unimplemented {- Field of type `Dict (String) (Evergreen.V24.Types.Amount)` was removed in V26. I need you to do something with the `p0.credits` value if you wish to keep the data, then remove this line. -})
                , day = (Unimplemented {- Field of type `Int` was removed in V26. I need you to do something with the `p0.day` value if you wish to keep the data, then remove this line. -})
                , debits = (Unimplemented {- Field of type `Dict (String) (Evergreen.V24.Types.Amount)` was removed in V26. I need you to do something with the `p0.debits` value if you wish to keep the data, then remove this line. -})
                , month = (Unimplemented {- Field of type `Int` was removed in V26. I need you to do something with the `p0.month` value if you wish to keep the data, then remove this line. -})
                , year = (Unimplemented {- Field of type `Int` was removed in V26. I need you to do something with the `p0.year` value if you wish to keep the data, then remove this line. -})
                }

        Evergreen.V24.Types.EditTransaction p0 ->
            (Unimplemented
             {- `EditTransaction` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.EditTransaction value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.DeleteTransaction p0 ->
            (Unimplemented
             {- `DeleteTransaction` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.DeleteTransaction value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.RequestTransactionDetails p0 ->
            (Unimplemented
             {- `RequestTransactionDetails` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.RequestTransactionDetails value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.RequestUserGroups p0 ->
            Evergreen.V26.Types.RequestUserGroups p0

        Evergreen.V24.Types.RequestGroupTransactions p0 ->
            Evergreen.V26.Types.RequestGroupTransactions p0

        Evergreen.V24.Types.RequestAllTransactions ->
            Evergreen.V26.Types.RequestAllTransactions

        Evergreen.V24.Types.CheckPassword p0 ->
            Evergreen.V26.Types.CheckPassword p0

        Evergreen.V24.Types.CheckAuthentication ->
            Evergreen.V26.Types.CheckAuthentication

        Evergreen.V24.Types.ImportJson p0 ->
            Evergreen.V26.Types.ImportJson p0

        notices ->
            {- @NOTICE `EditSpending {}` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `DeleteSpending Evergreen.V26.Types.SpendingId` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `RequestSpendingDetails Evergreen.V26.Types.SpendingId` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_ToFrontend : Evergreen.V24.Types.ToFrontend -> Evergreen.V26.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V24.Types.NoOpToFrontend ->
            Evergreen.V26.Types.NoOpToFrontend

        Evergreen.V24.Types.OperationSuccessful ->
            Evergreen.V26.Types.OperationSuccessful

        Evergreen.V24.Types.NameAlreadyExists p0 ->
            Evergreen.V26.Types.NameAlreadyExists p0

        Evergreen.V24.Types.InvalidPersonPrefix p0 ->
            Evergreen.V26.Types.InvalidPersonPrefix p0

        Evergreen.V24.Types.AutocompletePersonPrefix p0 ->
            Evergreen.V26.Types.AutocompletePersonPrefix p0

        Evergreen.V24.Types.InvalidGroupPrefix p0 ->
            Evergreen.V26.Types.InvalidGroupPrefix p0

        Evergreen.V24.Types.AutocompleteGroupPrefix p0 ->
            Evergreen.V26.Types.AutocompleteGroupPrefix p0

        Evergreen.V24.Types.ListUserGroups p0 ->
            Evergreen.V26.Types.ListUserGroups
                { user = p0.user
                , debitors = p0.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                , creditors = p0.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                }

        Evergreen.V24.Types.ListGroupTransactions p0 ->
            Evergreen.V26.Types.ListGroupTransactions
                { group = p0.group
                , transactions =
                    p0.transactions
                        |> List.map
                            (\rec1 ->
                                { transactionId = rec1.transactionId |> migrate_Types_TransactionId
                                , spendingId = (Unimplemented {- Type `Evergreen.V26.Types.SpendingId` was added in V26. I need you to set a default value. -})
                                , description = rec1.description
                                , year = rec1.year
                                , month = rec1.month
                                , day = rec1.day
                                , total = rec1.total |> migrate_Types_Amount
                                , share = rec1.share |> migrate_Types_Amount
                                }
                            )
                }

        Evergreen.V24.Types.AuthenticationStatus p0 ->
            Evergreen.V26.Types.AuthenticationStatus p0

        Evergreen.V24.Types.JsonExport p0 ->
            Evergreen.V26.Types.JsonExport p0

        Evergreen.V24.Types.TransactionError p0 ->
            (Unimplemented
             {- `TransactionError` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.TransactionError value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V24.Types.TransactionDetails p0 ->
            (Unimplemented
             {- `TransactionDetails` was removed or renamed in V26 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V24.Types.TransactionDetails value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        notices ->
            {- @NOTICE `SpendingError String` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `SpendingDetails {}` was added in V26.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_TransactionId : Evergreen.V24.Types.TransactionId -> Evergreen.V26.Types.TransactionId
migrate_Types_TransactionId old =
    old


migrate_Types_Year : Evergreen.V24.Types.Year -> Evergreen.V26.Types.Year
migrate_Types_Year old =
    { months = old.months |> Dict.map (\k -> migrate_Types_Month)
    , totalGroupCredits = old.totalGroupCredits |> Dict.map (\k -> Dict.map (\k -> migrate_Types_Amount))
    }
