module Evergreen.Migrate.V31 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V28.Types
import Evergreen.V31.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Set


frontendModel : Evergreen.V28.Types.FrontendModel -> ModelMigration Evergreen.V31.Types.FrontendModel Evergreen.V31.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V28.Types.BackendModel -> ModelMigration Evergreen.V31.Types.BackendModel Evergreen.V31.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V28.Types.FrontendMsg -> MsgMigration Evergreen.V31.Types.FrontendMsg Evergreen.V31.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V28.Types.ToBackend -> MsgMigration Evergreen.V31.Types.ToBackend Evergreen.V31.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V28.Types.BackendMsg -> MsgMigration Evergreen.V31.Types.BackendMsg Evergreen.V31.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V28.Types.ToFrontend -> MsgMigration Evergreen.V31.Types.ToFrontend Evergreen.V31.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_Transaction : Evergreen.V28.Types.Transaction -> Evergreen.V31.Types.Transaction
migrate_Types_Transaction old =
    { spendingId = old.spendingId
    , secondaryDescription = old.secondaryDescription
    , group = old.group
    , amount = old.amount |> migrate_Types_Amount
    , side = old.side |> migrate_Types_TransactionSide
    , groupMembersKey = old.groupMembersKey
    , groupMembers = old.groupMembers
    , status = old.status |> migrate_Types_TransactionStatus
    }


migrate_Types_BackendModel : Evergreen.V28.Types.BackendModel -> Evergreen.V31.Types.BackendModel
migrate_Types_BackendModel old =
    let
        groupDirectory =
            buildGroupDirectory old

        migratedTransactions =
            migrateLegacyTransactions groupDirectory.groupIds groupDirectory.groups old
    in
    { spendings = migrateLegacySpendings migratedTransactions.transactionIds old.spendings
    , groups = migratedTransactions.groups
    , persons = migrateLegacyPersons old
    , nextId = groupDirectory.nextId
    , totalGroupCredits = old.totalGroupCredits |> Dict.map (\_ -> Dict.map (\_ -> migrate_Types_Amount))
    , loggedInSessions = old.loggedInSessions
    }


invalidGroupId : Evergreen.V31.Types.GroupId
invalidGroupId =
    -1


type alias LegacyTransactionKey =
    ( Int, Int, ( Int, Int ) )


type alias GroupDirectory =
    { groupIds : Dict.Dict String Evergreen.V31.Types.GroupId
    , groups : Dict.Dict Evergreen.V31.Types.GroupId Evergreen.V31.Types.StoredGroup
    , nextId : Int
    }


type alias TransactionMigrationState =
    { groups : Dict.Dict Evergreen.V31.Types.GroupId Evergreen.V31.Types.StoredGroup
    , transactionIds : Dict.Dict LegacyTransactionKey Evergreen.V31.Types.TransactionId
    }


buildGroupDirectory : Evergreen.V28.Types.BackendModel -> GroupDirectory
buildGroupDirectory old =
    let
        personEntries =
            old.persons
                |> Dict.toList
                |> List.map
                    (\( personName, person ) ->
                        ( personName
                        , person.id
                        , { name = personName
                          , members = Dict.singleton person.id (Evergreen.V31.Types.Share 1)
                          , years = Dict.empty
                          , totalCredit = Evergreen.V31.Types.Amount 0
                          }
                        )
                    )

        maxPersonId =
            personEntries
                |> List.map (\( _, personId, _ ) -> personId)
                |> List.maximum
                |> Maybe.withDefault -1

        firstGroupId =
            max old.nextPersonId (maxPersonId + 1)

        personIds =
            personEntries
                |> List.map (\( personName, personId, _ ) -> ( personName, personId ))
                |> Dict.fromList

        personGroups =
            personEntries
                |> List.map (\( _, personId, group ) -> ( personId, group ))
                |> Dict.fromList

        ( groupIds, groups, nextId ) =
            old.groups
                |> Dict.toList
                |> List.foldl
                    (\( groupName, members ) ( groupIdsAcc, groupsAcc, nextIdAcc ) ->
                        let
                            groupId =
                                nextIdAcc
                        in
                        ( Dict.insert groupName groupId groupIdsAcc
                        , Dict.insert groupId (emptyStoredGroup groupName (migrateStoredGroupMembers personIds members)) groupsAcc
                        , nextIdAcc + 1
                        )
                    )
                    ( personIds, personGroups, firstGroupId )
    in
    { groupIds = groupIds
    , groups = groups
    , nextId = nextId
    }


emptyStoredGroup : String -> Evergreen.V31.Types.StoredGroupMembers -> Evergreen.V31.Types.StoredGroup
emptyStoredGroup groupName members =
    { name = groupName
    , members = members
    , years = Dict.empty
    , totalCredit = Evergreen.V31.Types.Amount 0
    }


migrateStoredGroupMembers :
    Dict.Dict String Evergreen.V31.Types.PersonId
    -> Evergreen.V28.Types.Group
    -> Evergreen.V31.Types.StoredGroupMembers
migrateStoredGroupMembers personIds oldMembers =
    oldMembers
        |> Dict.toList
        |> List.filterMap
            (\( personName, share ) ->
                Dict.get personName personIds
                    |> Maybe.map (\personId -> ( personId, migrate_Types_Share share ))
            )
        |> Dict.fromList


migrateLegacyPersons : Evergreen.V28.Types.BackendModel -> Dict.Dict Evergreen.V31.Types.PersonId Evergreen.V31.Types.Person
migrateLegacyPersons old =
    old.persons
        |> Dict.toList
        |> List.map
            (\( personName, person ) ->
                ( person.id
                , { name = personName
                  , belongsTo = belongsToKeys personName old
                  }
                )
            )
        |> Dict.fromList


belongsToKeys : String -> Evergreen.V28.Types.BackendModel -> Set.Set String
belongsToKeys personName old =
    old.years
        |> Dict.toList
        |> List.concatMap
            (\( _, year ) ->
                year.months
                    |> Dict.toList
                    |> List.concatMap
                        (\( _, month ) ->
                            month.days
                                |> Dict.toList
                                |> List.concatMap (\( _, day ) -> day.transactions |> Array.toList)
                        )
            )
        |> List.filter (\transaction -> Set.member personName transaction.groupMembers)
        |> List.map .groupMembersKey
        |> Set.fromList


migrateLegacyTransactions :
    Dict.Dict String Evergreen.V31.Types.GroupId
    -> Dict.Dict Evergreen.V31.Types.GroupId Evergreen.V31.Types.StoredGroup
    -> Evergreen.V28.Types.BackendModel
    -> TransactionMigrationState
migrateLegacyTransactions groupIds initialGroups old =
    old.years
        |> Dict.toList
        |> List.foldl
            (\( year, oldYear ) state ->
                oldYear.months
                    |> Dict.toList
                    |> List.foldl
                        (\( month, oldMonth ) monthState ->
                            oldMonth.days
                                |> Dict.toList
                                |> List.foldl
                                    (\( day, oldDay ) dayState ->
                                        oldDay.transactions
                                            |> Array.toIndexedList
                                            |> List.foldl
                                                (\( index, transaction ) transactionState ->
                                                    let
                                                        oldTransactionId =
                                                            { year = year
                                                            , month = month
                                                            , day = day
                                                            , index = index
                                                            }

                                                        newTransactionId =
                                                            nextTransactionId groupIds transactionState.groups oldTransactionId transaction.group
                                                    in
                                                    { groups =
                                                        transactionState.groups
                                                            |> Dict.update newTransactionId.groupId
                                                                (Maybe.map (appendLegacyTransaction year month day transaction))
                                                    , transactionIds =
                                                        Dict.insert (legacyTransactionKey oldTransactionId) newTransactionId transactionState.transactionIds
                                                    }
                                                )
                                                dayState
                                    )
                                    monthState
                        )
                        state
            )
            { groups = initialGroups
            , transactionIds = Dict.empty
            }


legacyTransactionKey : Evergreen.V28.Types.TransactionId -> LegacyTransactionKey
legacyTransactionKey transactionId =
    ( transactionId.year, transactionId.month, ( transactionId.day, transactionId.index ) )


nextTransactionId :
    Dict.Dict String Evergreen.V31.Types.GroupId
    -> Dict.Dict Evergreen.V31.Types.GroupId Evergreen.V31.Types.StoredGroup
    -> Evergreen.V28.Types.TransactionId
    -> String
    -> Evergreen.V31.Types.TransactionId
nextTransactionId groupIds groups oldTransactionId groupName =
    let
        groupId =
            Dict.get groupName groupIds
                |> Maybe.withDefault invalidGroupId
    in
    { groupId = groupId
    , year = oldTransactionId.year
    , month = oldTransactionId.month
    , day = oldTransactionId.day
    , index = groupDayLength groupId oldTransactionId.year oldTransactionId.month oldTransactionId.day groups
    }


groupDayLength :
    Evergreen.V31.Types.GroupId
    -> Int
    -> Int
    -> Int
    -> Dict.Dict Evergreen.V31.Types.GroupId Evergreen.V31.Types.StoredGroup
    -> Int
groupDayLength groupId year month day groups =
    groups
        |> Dict.get groupId
        |> Maybe.andThen (.years >> Dict.get year)
        |> Maybe.andThen (.months >> Dict.get month)
        |> Maybe.andThen (.days >> Dict.get day)
        |> Maybe.map (.transactions >> Array.length)
        |> Maybe.withDefault 0


appendLegacyTransaction :
    Int
    -> Int
    -> Int
    -> Evergreen.V28.Types.Transaction
    -> Evergreen.V31.Types.StoredGroup
    -> Evergreen.V31.Types.StoredGroup
appendLegacyTransaction year month day oldTransaction group =
    let
        totalCredit =
            legacyTransactionTotalCredit oldTransaction
    in
    { group
        | years =
            group.years
                |> Dict.update year
                    (Just << appendLegacyYear month day oldTransaction totalCredit)
        , totalCredit = addCredits group.totalCredit totalCredit
    }


appendLegacyYear :
    Int
    -> Int
    -> Evergreen.V28.Types.Transaction
    -> Evergreen.V31.Types.Amount Evergreen.V31.Types.Credit
    -> Maybe Evergreen.V31.Types.Year
    -> Evergreen.V31.Types.Year
appendLegacyYear month day oldTransaction totalCredit maybeYear =
    let
        year =
            maybeYear
                |> Maybe.withDefault
                    { months = Dict.empty
                    , totalCredit = Evergreen.V31.Types.Amount 0
                    }
    in
    { months =
        year.months
            |> Dict.update month
                (Just << appendLegacyMonth day oldTransaction totalCredit)
    , totalCredit = addCredits year.totalCredit totalCredit
    }


appendLegacyMonth :
    Int
    -> Evergreen.V28.Types.Transaction
    -> Evergreen.V31.Types.Amount Evergreen.V31.Types.Credit
    -> Maybe Evergreen.V31.Types.Month
    -> Evergreen.V31.Types.Month
appendLegacyMonth day oldTransaction totalCredit maybeMonth =
    let
        month =
            maybeMonth
                |> Maybe.withDefault
                    { days = Dict.empty
                    , totalCredit = Evergreen.V31.Types.Amount 0
                    }
    in
    { days =
        month.days
            |> Dict.update day
                (Just << appendLegacyDay oldTransaction totalCredit)
    , totalCredit = addCredits month.totalCredit totalCredit
    }


appendLegacyDay :
    Evergreen.V28.Types.Transaction
    -> Evergreen.V31.Types.Amount Evergreen.V31.Types.Credit
    -> Maybe Evergreen.V31.Types.Day
    -> Evergreen.V31.Types.Day
appendLegacyDay oldTransaction totalCredit maybeDay =
    let
        day =
            maybeDay
                |> Maybe.withDefault
                    { transactions = Array.empty
                    , totalCredit = Evergreen.V31.Types.Amount 0
                    }
    in
    { transactions = Array.push (migrateStoredTransaction oldTransaction) day.transactions
    , totalCredit = addCredits day.totalCredit totalCredit
    }


migrateStoredTransaction : Evergreen.V28.Types.Transaction -> Evergreen.V31.Types.Transaction
migrateStoredTransaction old =
    { spendingId = old.spendingId
    , secondaryDescription = old.secondaryDescription
    , group = old.group
    , amount = migrate_Types_Amount old.amount
    , side = migrate_Types_TransactionSide old.side
    , groupMembersKey = old.groupMembersKey
    , groupMembers = old.groupMembers
    , status = migrate_Types_TransactionStatus old.status
    }


legacyTransactionTotalCredit : Evergreen.V28.Types.Transaction -> Evergreen.V31.Types.Amount Evergreen.V31.Types.Credit
legacyTransactionTotalCredit transaction =
    if transaction.status == Evergreen.V28.Types.Active then
        case ( transaction.side, transaction.amount ) of
            ( Evergreen.V28.Types.CreditTransaction, Evergreen.V28.Types.Amount amount ) ->
                Evergreen.V31.Types.Amount amount

            ( Evergreen.V28.Types.DebitTransaction, Evergreen.V28.Types.Amount amount ) ->
                Evergreen.V31.Types.Amount -amount

    else
        Evergreen.V31.Types.Amount 0


addCredits :
    Evergreen.V31.Types.Amount Evergreen.V31.Types.Credit
    -> Evergreen.V31.Types.Amount Evergreen.V31.Types.Credit
    -> Evergreen.V31.Types.Amount Evergreen.V31.Types.Credit
addCredits (Evergreen.V31.Types.Amount left) (Evergreen.V31.Types.Amount right) =
    Evergreen.V31.Types.Amount (left + right)


migrateLegacySpendings :
    Dict.Dict LegacyTransactionKey Evergreen.V31.Types.TransactionId
    -> Array.Array Evergreen.V28.Types.Spending
    -> Array.Array Evergreen.V31.Types.Spending
migrateLegacySpendings transactionIds oldSpendings =
    oldSpendings
        |> Array.map
            (\spending ->
                { description = spending.description
                , total = migrate_Types_Amount spending.total
                , transactionIds = spending.transactionIds |> List.map (lookupTransactionId transactionIds)
                , status = migrate_Types_TransactionStatus spending.status
                }
            )


lookupTransactionId :
    Dict.Dict LegacyTransactionKey Evergreen.V31.Types.TransactionId
    -> Evergreen.V28.Types.TransactionId
    -> Evergreen.V31.Types.TransactionId
lookupTransactionId transactionIds oldTransactionId =
    Dict.get (legacyTransactionKey oldTransactionId) transactionIds
        |> Maybe.withDefault
            { groupId = invalidGroupId
            , year = oldTransactionId.year
            , month = oldTransactionId.month
            , day = oldTransactionId.day
            , index = oldTransactionId.index
            }


migrate_Types_FrontendModel : Evergreen.V28.Types.FrontendModel -> Evergreen.V31.Types.FrontendModel
migrate_Types_FrontendModel old =
    { page = old.page |> migrate_Types_Page
    , showDialog = old.showDialog |> Maybe.map migrate_Types_Dialog
    , errorMessage = old.errorMessage
    , user = old.user
    , nameValidity = old.nameValidity |> migrate_Types_NameValidity
    , userGroups =
        old.userGroups
            |> Maybe.map
                (\rec ->
                    { debitors = rec.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    , creditors = rec.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    }
                )
    , group = old.group
    , groupValidity = old.groupValidity |> migrate_Types_NameValidity
    , groupTransactions = []
    , key = old.key
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , checkingAuthentication = old.checkingAuthentication
    , theme = old.theme |> migrate_Types_Theme
    }


migrate_Types_AddGroupDialogModel : Evergreen.V28.Types.AddGroupDialogModel -> Evergreen.V31.Types.AddGroupDialogModel
migrate_Types_AddGroupDialogModel old =
    { name = old.name
    , nameInvalid = old.nameInvalid
    , members = old.members |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , submitted = old.submitted
    }


migrate_Types_AddPersonDialogModel : Evergreen.V28.Types.AddPersonDialogModel -> Evergreen.V31.Types.AddPersonDialogModel
migrate_Types_AddPersonDialogModel old =
    old


migrate_Types_AddSpendingDialogModel : Evergreen.V28.Types.AddSpendingDialogModel -> Evergreen.V31.Types.AddSpendingDialogModel
migrate_Types_AddSpendingDialogModel old =
    { spendingId = old.spendingId
    , description = old.description
    , total = old.total
    , date = old.date
    , today = old.today
    , dateText = old.dateText
    , datePickerModel = old.datePickerModel
    , credits = old.credits |> List.map migrate_Types_TransactionLine
    , debits = old.debits |> List.map migrate_Types_TransactionLine
    , submitted = old.submitted
    }


migrate_Types_Amount : Evergreen.V28.Types.Amount a_old -> Evergreen.V31.Types.Amount a_new
migrate_Types_Amount old =
    case old of
        Evergreen.V28.Types.Amount p0 ->
            Evergreen.V31.Types.Amount p0


migrate_Types_Dialog : Evergreen.V28.Types.Dialog -> Evergreen.V31.Types.Dialog
migrate_Types_Dialog old =
    case old of
        Evergreen.V28.Types.AddPersonDialog p0 ->
            Evergreen.V31.Types.AddPersonDialog (p0 |> migrate_Types_AddPersonDialogModel)

        Evergreen.V28.Types.AddGroupDialog p0 ->
            Evergreen.V31.Types.AddGroupDialog (p0 |> migrate_Types_AddGroupDialogModel)

        Evergreen.V28.Types.AddSpendingDialog p0 ->
            Evergreen.V31.Types.AddSpendingDialog (p0 |> migrate_Types_AddSpendingDialogModel)

        Evergreen.V28.Types.ConfirmDeleteDialog p0 ->
            Evergreen.V31.Types.ConfirmDeleteDialog p0

        Evergreen.V28.Types.PasswordDialog p0 ->
            Evergreen.V31.Types.PasswordDialog (p0 |> migrate_Types_PasswordDialogModel)


migrate_Types_FrontendMsg : Evergreen.V28.Types.FrontendMsg -> Evergreen.V31.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V28.Types.UrlClicked p0 ->
            Evergreen.V31.Types.UrlClicked p0

        Evergreen.V28.Types.UrlChanged p0 ->
            Evergreen.V31.Types.UrlChanged p0

        Evergreen.V28.Types.NoOpFrontendMsg ->
            Evergreen.V31.Types.NoOpFrontendMsg

        Evergreen.V28.Types.ShowAddPersonDialog ->
            Evergreen.V31.Types.ShowAddPersonDialog

        Evergreen.V28.Types.ShowAddGroupDialog ->
            Evergreen.V31.Types.ShowAddGroupDialog

        Evergreen.V28.Types.ShowAddSpendingDialog p0 ->
            case p0 of
                Nothing ->
                    Evergreen.V31.Types.ShowAddSpendingDialog Nothing

                Just _ ->
                    Evergreen.V31.Types.NoOpFrontendMsg

        Evergreen.V28.Types.ShowConfirmDeleteDialog p0 ->
            Evergreen.V31.Types.ShowConfirmDeleteDialog p0

        Evergreen.V28.Types.ConfirmDeleteSpending p0 ->
            Evergreen.V31.Types.ConfirmDeleteSpending p0

        Evergreen.V28.Types.SetToday p0 ->
            Evergreen.V31.Types.SetToday p0

        Evergreen.V28.Types.Submit ->
            Evergreen.V31.Types.Submit

        Evergreen.V28.Types.Cancel ->
            Evergreen.V31.Types.Cancel

        Evergreen.V28.Types.UpdateName p0 ->
            Evergreen.V31.Types.UpdateName p0

        Evergreen.V28.Types.AddMember p0 ->
            Evergreen.V31.Types.AddMember p0

        Evergreen.V28.Types.UpdateMember p0 p1 ->
            Evergreen.V31.Types.UpdateMember p0 p1

        Evergreen.V28.Types.UpdateShare p0 p1 ->
            Evergreen.V31.Types.UpdateShare p0 p1

        Evergreen.V28.Types.UpdateSpendingDate p0 ->
            Evergreen.V31.Types.UpdateSpendingDate p0

        Evergreen.V28.Types.UpdateSpendingTotal p0 ->
            Evergreen.V31.Types.UpdateSpendingTotal p0

        Evergreen.V28.Types.AddCreditor p0 ->
            Evergreen.V31.Types.AddCreditor p0

        Evergreen.V28.Types.RemoveCredit p0 ->
            Evergreen.V31.Types.RemoveCredit p0

        Evergreen.V28.Types.ToggleCreditDetails p0 ->
            Evergreen.V31.Types.ToggleCreditDetails p0

        Evergreen.V28.Types.UpdateCreditDate p0 p1 ->
            Evergreen.V31.Types.UpdateCreditDate p0 p1

        Evergreen.V28.Types.UpdateCreditSecondaryDescription p0 p1 ->
            Evergreen.V31.Types.UpdateCreditSecondaryDescription p0 p1

        Evergreen.V28.Types.UpdateCreditGroup p0 p1 ->
            Evergreen.V31.Types.UpdateCreditGroup p0 p1

        Evergreen.V28.Types.UpdateCreditAmount p0 p1 ->
            Evergreen.V31.Types.UpdateCreditAmount p0 p1

        Evergreen.V28.Types.AddDebitor p0 ->
            Evergreen.V31.Types.AddDebitor p0

        Evergreen.V28.Types.RemoveDebit p0 ->
            Evergreen.V31.Types.RemoveDebit p0

        Evergreen.V28.Types.ToggleDebitDetails p0 ->
            Evergreen.V31.Types.ToggleDebitDetails p0

        Evergreen.V28.Types.UpdateDebitDate p0 p1 ->
            Evergreen.V31.Types.UpdateDebitDate p0 p1

        Evergreen.V28.Types.UpdateDebitSecondaryDescription p0 p1 ->
            Evergreen.V31.Types.UpdateDebitSecondaryDescription p0 p1

        Evergreen.V28.Types.UpdateDebitGroup p0 p1 ->
            Evergreen.V31.Types.UpdateDebitGroup p0 p1

        Evergreen.V28.Types.UpdateDebitAmount p0 p1 ->
            Evergreen.V31.Types.UpdateDebitAmount p0 p1

        Evergreen.V28.Types.UpdateGroupName p0 ->
            Evergreen.V31.Types.UpdateGroupName p0

        Evergreen.V28.Types.UpdatePassword p0 ->
            Evergreen.V31.Types.UpdatePassword p0

        Evergreen.V28.Types.UpdateJson p0 ->
            Evergreen.V31.Types.UpdateJson p0

        Evergreen.V28.Types.ViewportChanged p0 p1 ->
            Evergreen.V31.Types.ViewportChanged p0 p1

        Evergreen.V28.Types.ToggleTheme ->
            Evergreen.V31.Types.ToggleTheme


migrate_Types_Group : Evergreen.V28.Types.Group -> Evergreen.V31.Types.Group
migrate_Types_Group old =
    old |> Dict.map (\k -> migrate_Types_Share)


migrate_Types_NameValidity : Evergreen.V28.Types.NameValidity -> Evergreen.V31.Types.NameValidity
migrate_Types_NameValidity old =
    case old of
        Evergreen.V28.Types.Complete ->
            Evergreen.V31.Types.Complete

        Evergreen.V28.Types.Incomplete ->
            Evergreen.V31.Types.Incomplete

        Evergreen.V28.Types.InvalidPrefix ->
            Evergreen.V31.Types.InvalidPrefix


migrate_Types_Page : Evergreen.V28.Types.Page -> Evergreen.V31.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V28.Types.Home ->
            Evergreen.V31.Types.Home

        Evergreen.V28.Types.Json p0 ->
            Evergreen.V31.Types.Json p0

        Evergreen.V28.Types.Import p0 ->
            Evergreen.V31.Types.Import p0

        Evergreen.V28.Types.NotFound ->
            Evergreen.V31.Types.NotFound


migrate_Types_PasswordDialogModel : Evergreen.V28.Types.PasswordDialogModel -> Evergreen.V31.Types.PasswordDialogModel
migrate_Types_PasswordDialogModel old =
    old


migrate_Types_Share : Evergreen.V28.Types.Share -> Evergreen.V31.Types.Share
migrate_Types_Share old =
    case old of
        Evergreen.V28.Types.Share p0 ->
            Evergreen.V31.Types.Share p0


migrate_Types_Spending : Evergreen.V28.Types.Spending -> Evergreen.V31.Types.Spending
migrate_Types_Spending old =
    { description = old.description
    , total = old.total |> migrate_Types_Amount
    , transactionIds = old.transactionIds |> List.map migrate_Types_TransactionId
    , status = old.status |> migrate_Types_TransactionStatus
    }


migrate_Types_SpendingTransaction : Evergreen.V28.Types.SpendingTransaction -> Evergreen.V31.Types.SpendingTransaction
migrate_Types_SpendingTransaction old =
    { year = old.year
    , month = old.month
    , day = old.day
    , secondaryDescription = old.secondaryDescription
    , group = old.group
    , amount = old.amount |> migrate_Types_Amount
    , side = old.side |> migrate_Types_TransactionSide
    }


migrate_Types_Theme : Evergreen.V28.Types.Theme -> Evergreen.V31.Types.Theme
migrate_Types_Theme old =
    case old of
        Evergreen.V28.Types.LightMode ->
            Evergreen.V31.Types.LightMode

        Evergreen.V28.Types.DarkMode ->
            Evergreen.V31.Types.DarkMode


migrate_Types_ToFrontend : Evergreen.V28.Types.ToFrontend -> Evergreen.V31.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V28.Types.NoOpToFrontend ->
            Evergreen.V31.Types.NoOpToFrontend

        Evergreen.V28.Types.OperationSuccessful ->
            Evergreen.V31.Types.OperationSuccessful

        Evergreen.V28.Types.NameAlreadyExists p0 ->
            Evergreen.V31.Types.NameAlreadyExists p0

        Evergreen.V28.Types.InvalidPersonPrefix p0 ->
            Evergreen.V31.Types.InvalidPersonPrefix p0

        Evergreen.V28.Types.AutocompletePersonPrefix p0 ->
            Evergreen.V31.Types.AutocompletePersonPrefix p0

        Evergreen.V28.Types.InvalidGroupPrefix p0 ->
            Evergreen.V31.Types.InvalidGroupPrefix p0

        Evergreen.V28.Types.AutocompleteGroupPrefix p0 ->
            Evergreen.V31.Types.AutocompleteGroupPrefix p0

        Evergreen.V28.Types.ListUserGroups p0 ->
            Evergreen.V31.Types.ListUserGroups
                { user = p0.user
                , debitors = p0.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                , creditors = p0.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                }

        Evergreen.V28.Types.ListGroupTransactions p0 ->
            Evergreen.V31.Types.ListGroupTransactions
                { group = p0.group
                , transactions = []
                }

        Evergreen.V28.Types.AuthenticationStatus p0 ->
            Evergreen.V31.Types.AuthenticationStatus p0

        Evergreen.V28.Types.JsonExport p0 ->
            Evergreen.V31.Types.JsonExport p0

        Evergreen.V28.Types.SpendingError p0 ->
            Evergreen.V31.Types.SpendingError p0

        Evergreen.V28.Types.SpendingDetails p0 ->
            Evergreen.V31.Types.SpendingDetails
                { spendingId = p0.spendingId
                , description = p0.description
                , total = p0.total |> migrate_Types_Amount
                , transactions = p0.transactions |> List.map migrate_Types_SpendingTransaction
                }


migrate_Types_TransactionId : Evergreen.V28.Types.TransactionId -> Evergreen.V31.Types.TransactionId
migrate_Types_TransactionId old =
    { groupId = invalidGroupId
    , year = old.year
    , month = old.month
    , day = old.day
    , index = old.index
    }


migrate_Types_TransactionLine : Evergreen.V28.Types.TransactionLine -> Evergreen.V31.Types.TransactionLine
migrate_Types_TransactionLine old =
    { date = old.date
    , dateText = old.dateText
    , datePickerModel = old.datePickerModel
    , secondaryDescription = old.secondaryDescription
    , detailsExpanded = old.detailsExpanded
    , group = old.group
    , amount = old.amount
    , nameValidity = old.nameValidity |> migrate_Types_NameValidity
    }


migrate_Types_TransactionSide : Evergreen.V28.Types.TransactionSide -> Evergreen.V31.Types.TransactionSide
migrate_Types_TransactionSide old =
    case old of
        Evergreen.V28.Types.CreditTransaction ->
            Evergreen.V31.Types.CreditTransaction

        Evergreen.V28.Types.DebitTransaction ->
            Evergreen.V31.Types.DebitTransaction


migrate_Types_TransactionStatus : Evergreen.V28.Types.TransactionStatus -> Evergreen.V31.Types.TransactionStatus
migrate_Types_TransactionStatus old =
    case old of
        Evergreen.V28.Types.Active ->
            Evergreen.V31.Types.Active

        Evergreen.V28.Types.Deleted ->
            Evergreen.V31.Types.Deleted

        Evergreen.V28.Types.Replaced ->
            Evergreen.V31.Types.Replaced
