module Evergreen.Migrate.V33 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V31.Types
import Evergreen.V33.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V31.Types.FrontendModel -> ModelMigration Evergreen.V33.Types.FrontendModel Evergreen.V33.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V31.Types.BackendModel -> ModelMigration Evergreen.V33.Types.BackendModel Evergreen.V33.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V31.Types.FrontendMsg -> MsgMigration Evergreen.V33.Types.FrontendMsg Evergreen.V33.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V31.Types.ToBackend -> MsgMigration Evergreen.V33.Types.ToBackend Evergreen.V33.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V31.Types.BackendMsg -> MsgMigration Evergreen.V33.Types.BackendMsg Evergreen.V33.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V31.Types.ToFrontend -> MsgMigration Evergreen.V33.Types.ToFrontend Evergreen.V33.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V31.Types.BackendModel -> Evergreen.V33.Types.BackendModel
migrate_Types_BackendModel old =
    { spendings = old.spendings |> Array.map migrate_Types_Spending
    , groups = old.groups |> Dict.map (\k -> migrate_Types_StoredGroup)
    , persons = old.persons
    , nextId = old.nextId
    , totalGroupCredits = old.totalGroupCredits |> Dict.map (\_ -> Dict.map (\_ -> migrate_Types_Amount))
    , loggedInSessions = old.loggedInSessions
    }


migrate_Types_FrontendModel : Evergreen.V31.Types.FrontendModel -> Evergreen.V33.Types.FrontendModel
migrate_Types_FrontendModel old =
    { page = old.page |> migrate_Types_Page
    , showDialog = old.showDialog |> Maybe.map migrate_Types_Dialog
    , errorMessage = old.errorMessage
    , user = old.user
    , nameValidity = old.nameValidity |> migrate_Types_NameValidity
    , userGroups =
        old.userGroups
            |> Maybe.map
                (\rec ->
                    { debitors = rec.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    , creditors = rec.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    }
                )
    , group = old.group
    , groupValidity = old.groupValidity |> migrate_Types_NameValidity
    , groupTransactions =
        old.groupTransactions
            |> List.map
                (\rec ->
                    { transactionId = rec.transactionId |> migrate_Types_TransactionId
                    , spendingId = rec.spendingId
                    , description = rec.description
                    , year = rec.year
                    , month = rec.month
                    , day = rec.day
                    , total = rec.total |> migrate_Types_Amount
                    , share = rec.share |> migrate_Types_Amount
                    , checked = False
                    }
                )
    , key = old.key
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , checkingAuthentication = old.checkingAuthentication
    , theme = old.theme |> migrate_Types_Theme
    }


migrate_Types_AddGroupDialogModel : Evergreen.V31.Types.AddGroupDialogModel -> Evergreen.V33.Types.AddGroupDialogModel
migrate_Types_AddGroupDialogModel old =
    { name = old.name
    , nameInvalid = old.nameInvalid
    , members = old.members |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , submitted = old.submitted
    }


migrate_Types_AddPersonDialogModel : Evergreen.V31.Types.AddPersonDialogModel -> Evergreen.V33.Types.AddPersonDialogModel
migrate_Types_AddPersonDialogModel old =
    old


migrate_Types_AddSpendingDialogModel : Evergreen.V31.Types.AddSpendingDialogModel -> Evergreen.V33.Types.AddSpendingDialogModel
migrate_Types_AddSpendingDialogModel old =
    { spendingId = old.spendingId
    , description = old.description
    , total = old.total
    , date = old.date
    , today = old.today
    , dateText = old.dateText
    , datePickerModel = old.datePickerModel
    , credits = old.credits |> List.map migrate_Types_TransactionLine
    , debits = old.debits |> List.map migrate_Types_TransactionLine
    , submitted = old.submitted
    }


migrate_Types_Amount : Evergreen.V31.Types.Amount a_old -> Evergreen.V33.Types.Amount a_new
migrate_Types_Amount old =
    case old of
        Evergreen.V31.Types.Amount p0 ->
            Evergreen.V33.Types.Amount p0


migrate_Types_Day : Evergreen.V31.Types.Day -> Evergreen.V33.Types.Day
migrate_Types_Day old =
    { transactions = old.transactions |> Array.map migrate_Types_Transaction
    , totalCredit = old.totalCredit |> migrate_Types_Amount
    }


migrate_Types_Dialog : Evergreen.V31.Types.Dialog -> Evergreen.V33.Types.Dialog
migrate_Types_Dialog old =
    case old of
        Evergreen.V31.Types.AddPersonDialog p0 ->
            Evergreen.V33.Types.AddPersonDialog (p0 |> migrate_Types_AddPersonDialogModel)

        Evergreen.V31.Types.AddGroupDialog p0 ->
            Evergreen.V33.Types.AddGroupDialog (p0 |> migrate_Types_AddGroupDialogModel)

        Evergreen.V31.Types.AddSpendingDialog p0 ->
            Evergreen.V33.Types.AddSpendingDialog (p0 |> migrate_Types_AddSpendingDialogModel)

        Evergreen.V31.Types.ConfirmDeleteDialog p0 ->
            Evergreen.V33.Types.ConfirmDeleteDialog p0

        Evergreen.V31.Types.PasswordDialog p0 ->
            Evergreen.V33.Types.PasswordDialog (p0 |> migrate_Types_PasswordDialogModel)


migrate_Types_FrontendMsg : Evergreen.V31.Types.FrontendMsg -> Evergreen.V33.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V31.Types.UrlClicked p0 ->
            Evergreen.V33.Types.UrlClicked p0

        Evergreen.V31.Types.UrlChanged p0 ->
            Evergreen.V33.Types.UrlChanged p0

        Evergreen.V31.Types.NoOpFrontendMsg ->
            Evergreen.V33.Types.NoOpFrontendMsg

        Evergreen.V31.Types.ShowAddPersonDialog ->
            Evergreen.V33.Types.ShowAddPersonDialog

        Evergreen.V31.Types.ShowAddGroupDialog ->
            Evergreen.V33.Types.ShowAddGroupDialog

        Evergreen.V31.Types.ShowAddSpendingDialog p0 ->
            Evergreen.V33.Types.ShowAddSpendingDialog p0

        Evergreen.V31.Types.ShowConfirmDeleteDialog p0 ->
            Evergreen.V33.Types.ShowConfirmDeleteDialog p0

        Evergreen.V31.Types.ConfirmDeleteSpending p0 ->
            Evergreen.V33.Types.ConfirmDeleteSpending p0

        Evergreen.V31.Types.SetToday p0 ->
            Evergreen.V33.Types.SetToday p0

        Evergreen.V31.Types.Submit ->
            Evergreen.V33.Types.Submit

        Evergreen.V31.Types.Cancel ->
            Evergreen.V33.Types.Cancel

        Evergreen.V31.Types.UpdateName p0 ->
            Evergreen.V33.Types.UpdateName p0

        Evergreen.V31.Types.AddMember p0 ->
            Evergreen.V33.Types.AddMember p0

        Evergreen.V31.Types.UpdateMember p0 p1 ->
            Evergreen.V33.Types.UpdateMember p0 p1

        Evergreen.V31.Types.UpdateShare p0 p1 ->
            Evergreen.V33.Types.UpdateShare p0 p1

        Evergreen.V31.Types.UpdateSpendingDate p0 ->
            Evergreen.V33.Types.UpdateSpendingDate p0

        Evergreen.V31.Types.UpdateSpendingTotal p0 ->
            Evergreen.V33.Types.UpdateSpendingTotal p0

        Evergreen.V31.Types.AddCreditor p0 ->
            Evergreen.V33.Types.AddCreditor p0

        Evergreen.V31.Types.RemoveCredit p0 ->
            Evergreen.V33.Types.RemoveCredit p0

        Evergreen.V31.Types.ToggleCreditDetails p0 ->
            Evergreen.V33.Types.ToggleCreditDetails p0

        Evergreen.V31.Types.UpdateCreditDate p0 p1 ->
            Evergreen.V33.Types.UpdateCreditDate p0 p1

        Evergreen.V31.Types.UpdateCreditSecondaryDescription p0 p1 ->
            Evergreen.V33.Types.UpdateCreditSecondaryDescription p0 p1

        Evergreen.V31.Types.UpdateCreditGroup p0 p1 ->
            Evergreen.V33.Types.UpdateCreditGroup p0 p1

        Evergreen.V31.Types.UpdateCreditAmount p0 p1 ->
            Evergreen.V33.Types.UpdateCreditAmount p0 p1

        Evergreen.V31.Types.AddDebitor p0 ->
            Evergreen.V33.Types.AddDebitor p0

        Evergreen.V31.Types.RemoveDebit p0 ->
            Evergreen.V33.Types.RemoveDebit p0

        Evergreen.V31.Types.ToggleDebitDetails p0 ->
            Evergreen.V33.Types.ToggleDebitDetails p0

        Evergreen.V31.Types.UpdateDebitDate p0 p1 ->
            Evergreen.V33.Types.UpdateDebitDate p0 p1

        Evergreen.V31.Types.UpdateDebitSecondaryDescription p0 p1 ->
            Evergreen.V33.Types.UpdateDebitSecondaryDescription p0 p1

        Evergreen.V31.Types.UpdateDebitGroup p0 p1 ->
            Evergreen.V33.Types.UpdateDebitGroup p0 p1

        Evergreen.V31.Types.UpdateDebitAmount p0 p1 ->
            Evergreen.V33.Types.UpdateDebitAmount p0 p1

        Evergreen.V31.Types.UpdateGroupName p0 ->
            Evergreen.V33.Types.UpdateGroupName p0

        Evergreen.V31.Types.UpdatePassword p0 ->
            Evergreen.V33.Types.UpdatePassword p0

        Evergreen.V31.Types.UpdateJson p0 ->
            Evergreen.V33.Types.UpdateJson p0

        Evergreen.V31.Types.ViewportChanged p0 p1 ->
            Evergreen.V33.Types.ViewportChanged p0 p1

        Evergreen.V31.Types.ToggleTheme ->
            Evergreen.V33.Types.ToggleTheme


migrate_Types_Group : Evergreen.V31.Types.Group -> Evergreen.V33.Types.Group
migrate_Types_Group old =
    old |> Dict.map (\k -> migrate_Types_Share)


migrate_Types_Month : Evergreen.V31.Types.Month -> Evergreen.V33.Types.Month
migrate_Types_Month old =
    { days = old.days |> Dict.map (\k -> migrate_Types_Day)
    , totalCredit = old.totalCredit |> migrate_Types_Amount
    }


migrate_Types_NameValidity : Evergreen.V31.Types.NameValidity -> Evergreen.V33.Types.NameValidity
migrate_Types_NameValidity old =
    case old of
        Evergreen.V31.Types.Complete ->
            Evergreen.V33.Types.Complete

        Evergreen.V31.Types.Incomplete ->
            Evergreen.V33.Types.Incomplete

        Evergreen.V31.Types.InvalidPrefix ->
            Evergreen.V33.Types.InvalidPrefix


migrate_Types_Page : Evergreen.V31.Types.Page -> Evergreen.V33.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V31.Types.Home ->
            Evergreen.V33.Types.Home

        Evergreen.V31.Types.Json p0 ->
            Evergreen.V33.Types.Json p0

        Evergreen.V31.Types.Import p0 ->
            Evergreen.V33.Types.Import p0

        Evergreen.V31.Types.NotFound ->
            Evergreen.V33.Types.NotFound


migrate_Types_PasswordDialogModel : Evergreen.V31.Types.PasswordDialogModel -> Evergreen.V33.Types.PasswordDialogModel
migrate_Types_PasswordDialogModel old =
    old


migrate_Types_Share : Evergreen.V31.Types.Share -> Evergreen.V33.Types.Share
migrate_Types_Share old =
    case old of
        Evergreen.V31.Types.Share p0 ->
            Evergreen.V33.Types.Share p0


migrate_Types_Spending : Evergreen.V31.Types.Spending -> Evergreen.V33.Types.Spending
migrate_Types_Spending old =
    { description = old.description
    , total = old.total |> migrate_Types_Amount
    , transactionIds = old.transactionIds
    , status = old.status |> migrate_Types_TransactionStatus
    }


migrate_Types_SpendingTransaction : Evergreen.V31.Types.SpendingTransaction -> Evergreen.V33.Types.SpendingTransaction
migrate_Types_SpendingTransaction old =
    { year = old.year
    , month = old.month
    , day = old.day
    , secondaryDescription = old.secondaryDescription
    , group = old.group
    , amount = old.amount |> migrate_Types_Amount
    , side = old.side |> migrate_Types_TransactionSide
    }


migrate_Types_StoredGroup : Evergreen.V31.Types.StoredGroup -> Evergreen.V33.Types.StoredGroup
migrate_Types_StoredGroup old =
    { name = old.name
    , members = old.members |> migrate_Types_StoredGroupMembers
    , years = old.years |> Dict.map (\k -> migrate_Types_Year)
    , totalCredit = old.totalCredit |> migrate_Types_Amount
    }


migrate_Types_StoredGroupMembers : Evergreen.V31.Types.StoredGroupMembers -> Evergreen.V33.Types.StoredGroupMembers
migrate_Types_StoredGroupMembers old =
    old |> Dict.map (\k -> migrate_Types_Share)


migrate_Types_Theme : Evergreen.V31.Types.Theme -> Evergreen.V33.Types.Theme
migrate_Types_Theme old =
    case old of
        Evergreen.V31.Types.LightMode ->
            Evergreen.V33.Types.LightMode

        Evergreen.V31.Types.DarkMode ->
            Evergreen.V33.Types.DarkMode


migrate_Types_ToBackend : Evergreen.V31.Types.ToBackend -> Evergreen.V33.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V31.Types.NoOpToBackend ->
            Evergreen.V33.Types.NoOpToBackend

        Evergreen.V31.Types.CheckValidName p0 ->
            Evergreen.V33.Types.CheckValidName p0

        Evergreen.V31.Types.AutocompletePerson p0 ->
            Evergreen.V33.Types.AutocompletePerson p0

        Evergreen.V31.Types.AutocompleteGroup p0 ->
            Evergreen.V33.Types.AutocompleteGroup p0

        Evergreen.V31.Types.CreatePerson p0 ->
            Evergreen.V33.Types.CreatePerson p0

        Evergreen.V31.Types.CreateGroup p0 p1 ->
            Evergreen.V33.Types.CreateGroup p0 (p1 |> Dict.map (\k -> migrate_Types_Share))

        Evergreen.V31.Types.CreateSpending p0 ->
            Evergreen.V33.Types.CreateSpending
                { description = p0.description
                , total = p0.total |> migrate_Types_Amount
                , transactions = p0.transactions |> List.map migrate_Types_SpendingTransaction
                }

        Evergreen.V31.Types.EditSpending p0 ->
            Evergreen.V33.Types.EditSpending
                { spendingId = p0.spendingId
                , description = p0.description
                , total = p0.total |> migrate_Types_Amount
                , transactions = p0.transactions |> List.map migrate_Types_SpendingTransaction
                }

        Evergreen.V31.Types.DeleteSpending p0 ->
            Evergreen.V33.Types.DeleteSpending p0

        Evergreen.V31.Types.RequestSpendingDetails p0 ->
            Evergreen.V33.Types.RequestSpendingDetails p0

        Evergreen.V31.Types.RequestUserGroups p0 ->
            Evergreen.V33.Types.RequestUserGroups p0

        Evergreen.V31.Types.RequestGroupTransactions p0 ->
            Evergreen.V33.Types.RequestGroupTransactions p0

        Evergreen.V31.Types.RequestAllTransactions ->
            Evergreen.V33.Types.RequestAllTransactions

        Evergreen.V31.Types.CheckPassword p0 ->
            Evergreen.V33.Types.CheckPassword p0

        Evergreen.V31.Types.CheckAuthentication ->
            Evergreen.V33.Types.CheckAuthentication

        Evergreen.V31.Types.ImportJson p0 ->
            Evergreen.V33.Types.ImportJson p0


migrate_Types_ToFrontend : Evergreen.V31.Types.ToFrontend -> Evergreen.V33.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V31.Types.NoOpToFrontend ->
            Evergreen.V33.Types.NoOpToFrontend

        Evergreen.V31.Types.OperationSuccessful ->
            Evergreen.V33.Types.OperationSuccessful

        Evergreen.V31.Types.NameAlreadyExists p0 ->
            Evergreen.V33.Types.NameAlreadyExists p0

        Evergreen.V31.Types.InvalidPersonPrefix p0 ->
            Evergreen.V33.Types.InvalidPersonPrefix p0

        Evergreen.V31.Types.AutocompletePersonPrefix p0 ->
            Evergreen.V33.Types.AutocompletePersonPrefix p0

        Evergreen.V31.Types.InvalidGroupPrefix p0 ->
            Evergreen.V33.Types.InvalidGroupPrefix p0

        Evergreen.V31.Types.AutocompleteGroupPrefix p0 ->
            Evergreen.V33.Types.AutocompleteGroupPrefix p0

        Evergreen.V31.Types.ListUserGroups p0 ->
            Evergreen.V33.Types.ListUserGroups
                { user = p0.user
                , debitors = p0.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                , creditors = p0.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                }

        Evergreen.V31.Types.ListGroupTransactions p0 ->
            Evergreen.V33.Types.ListGroupTransactions
                { group = p0.group
                , transactions =
                    p0.transactions
                        |> List.map
                            (\rec1 ->
                                { transactionId = rec1.transactionId |> migrate_Types_TransactionId
                                , spendingId = rec1.spendingId
                                , description = rec1.description
                                , year = rec1.year
                                , month = rec1.month
                                , day = rec1.day
                                , total = rec1.total |> migrate_Types_Amount
                                , share = rec1.share |> migrate_Types_Amount
                                , checked = False
                                }
                            )
                }

        Evergreen.V31.Types.AuthenticationStatus p0 ->
            Evergreen.V33.Types.AuthenticationStatus p0

        Evergreen.V31.Types.JsonExport p0 ->
            Evergreen.V33.Types.JsonExport p0

        Evergreen.V31.Types.SpendingError p0 ->
            Evergreen.V33.Types.SpendingError p0

        Evergreen.V31.Types.SpendingDetails p0 ->
            Evergreen.V33.Types.SpendingDetails
                { spendingId = p0.spendingId
                , description = p0.description
                , total = p0.total |> migrate_Types_Amount
                , transactions = p0.transactions |> List.map migrate_Types_SpendingTransaction
                }


migrate_Types_Transaction : Evergreen.V31.Types.Transaction -> Evergreen.V33.Types.Transaction
migrate_Types_Transaction old =
    { spendingId = old.spendingId
    , secondaryDescription = old.secondaryDescription
    , group = old.group
    , amount = old.amount |> migrate_Types_Amount
    , side = old.side |> migrate_Types_TransactionSide
    , groupMembersKey = old.groupMembersKey
    , groupMembers = old.groupMembers
    , status = old.status |> migrate_Types_TransactionStatus
    , checked = False
    }


migrate_Types_TransactionId : Evergreen.V31.Types.TransactionId -> Evergreen.V33.Types.TransactionId
migrate_Types_TransactionId old =
    old


migrate_Types_TransactionLine : Evergreen.V31.Types.TransactionLine -> Evergreen.V33.Types.TransactionLine
migrate_Types_TransactionLine old =
    { date = old.date
    , dateText = old.dateText
    , datePickerModel = old.datePickerModel
    , secondaryDescription = old.secondaryDescription
    , detailsExpanded = old.detailsExpanded
    , group = old.group
    , amount = old.amount
    , nameValidity = old.nameValidity |> migrate_Types_NameValidity
    }


migrate_Types_TransactionSide : Evergreen.V31.Types.TransactionSide -> Evergreen.V33.Types.TransactionSide
migrate_Types_TransactionSide old =
    case old of
        Evergreen.V31.Types.CreditTransaction ->
            Evergreen.V33.Types.CreditTransaction

        Evergreen.V31.Types.DebitTransaction ->
            Evergreen.V33.Types.DebitTransaction


migrate_Types_TransactionStatus : Evergreen.V31.Types.TransactionStatus -> Evergreen.V33.Types.TransactionStatus
migrate_Types_TransactionStatus old =
    case old of
        Evergreen.V31.Types.Active ->
            Evergreen.V33.Types.Active

        Evergreen.V31.Types.Deleted ->
            Evergreen.V33.Types.Deleted

        Evergreen.V31.Types.Replaced ->
            Evergreen.V33.Types.Replaced


migrate_Types_Year : Evergreen.V31.Types.Year -> Evergreen.V33.Types.Year
migrate_Types_Year old =
    { months = old.months |> Dict.map (\k -> migrate_Types_Month)
    , totalCredit = old.totalCredit |> migrate_Types_Amount
    }
