module Evergreen.Migrate.V37 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V35.Types
import Evergreen.V37.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V35.Types.FrontendModel -> ModelMigration Evergreen.V37.Types.FrontendModel Evergreen.V37.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V35.Types.BackendModel -> ModelMigration Evergreen.V37.Types.BackendModel Evergreen.V37.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V35.Types.FrontendMsg -> MsgMigration Evergreen.V37.Types.FrontendMsg Evergreen.V37.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V35.Types.ToBackend -> MsgMigration Evergreen.V37.Types.ToBackend Evergreen.V37.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V35.Types.BackendMsg -> MsgMigration Evergreen.V37.Types.BackendMsg Evergreen.V37.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V35.Types.ToFrontend -> MsgMigration Evergreen.V37.Types.ToFrontend Evergreen.V37.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendMsg : Evergreen.V35.Types.FrontendMsg -> Evergreen.V37.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V35.Types.UrlClicked p0 ->
            Evergreen.V37.Types.UrlClicked p0

        Evergreen.V35.Types.UrlChanged p0 ->
            Evergreen.V37.Types.UrlChanged p0

        Evergreen.V35.Types.NoOpFrontendMsg ->
            Evergreen.V37.Types.NoOpFrontendMsg

        Evergreen.V35.Types.ShowAddPersonDialog ->
            Evergreen.V37.Types.ShowAddPersonDialog

        Evergreen.V35.Types.ShowAddGroupDialog ->
            Evergreen.V37.Types.ShowAddGroupDialog

        Evergreen.V35.Types.ShowAddSpendingDialog p0 ->
            Evergreen.V37.Types.ShowAddSpendingDialog p0

        Evergreen.V35.Types.ShowConfirmDeleteDialog p0 ->
            Evergreen.V37.Types.ShowConfirmDeleteDialog p0

        Evergreen.V35.Types.ConfirmDeleteSpending p0 ->
            Evergreen.V37.Types.ConfirmDeleteSpending p0

        Evergreen.V35.Types.ToggleTransactionChecked p0 ->
            Evergreen.V37.Types.ToggleTransactionChecked (p0 |> migrate_Types_TransactionId)

        Evergreen.V35.Types.ToggleGroupTransactionMonthFold p0 ->
            Evergreen.V37.Types.ToggleGroupTransactionMonthFold (p0 |> migrate_Types_GroupTransactionsCursor)

        Evergreen.V35.Types.SetToday p0 ->
            Evergreen.V37.Types.SetToday p0

        Evergreen.V35.Types.Submit ->
            Evergreen.V37.Types.Submit

        Evergreen.V35.Types.Cancel ->
            Evergreen.V37.Types.Cancel

        Evergreen.V35.Types.UpdateName p0 ->
            Evergreen.V37.Types.UpdateName p0

        Evergreen.V35.Types.AddMember p0 ->
            Evergreen.V37.Types.AddMember p0

        Evergreen.V35.Types.UpdateMember p0 p1 ->
            Evergreen.V37.Types.UpdateMember p0 p1

        Evergreen.V35.Types.UpdateShare p0 p1 ->
            Evergreen.V37.Types.UpdateShare p0 p1

        Evergreen.V35.Types.UpdateSpendingDate p0 ->
            Evergreen.V37.Types.UpdateSpendingDate p0

        Evergreen.V35.Types.UpdateSpendingTotal p0 ->
            Evergreen.V37.Types.UpdateSpendingTotal p0

        Evergreen.V35.Types.AddCreditor p0 ->
            Evergreen.V37.Types.AddCreditor p0

        Evergreen.V35.Types.RemoveCredit p0 ->
            Evergreen.V37.Types.RemoveCredit p0

        Evergreen.V35.Types.ToggleCreditDetails p0 ->
            Evergreen.V37.Types.ToggleCreditDetails p0

        Evergreen.V35.Types.UpdateCreditDate p0 p1 ->
            Evergreen.V37.Types.UpdateCreditDate p0 p1

        Evergreen.V35.Types.UpdateCreditSecondaryDescription p0 p1 ->
            Evergreen.V37.Types.UpdateCreditSecondaryDescription p0 p1

        Evergreen.V35.Types.UpdateCreditGroup p0 p1 ->
            Evergreen.V37.Types.UpdateCreditGroup p0 p1

        Evergreen.V35.Types.UpdateCreditAmount p0 p1 ->
            Evergreen.V37.Types.UpdateCreditAmount p0 p1

        Evergreen.V35.Types.AddDebitor p0 ->
            Evergreen.V37.Types.AddDebitor p0

        Evergreen.V35.Types.RemoveDebit p0 ->
            Evergreen.V37.Types.RemoveDebit p0

        Evergreen.V35.Types.ToggleDebitDetails p0 ->
            Evergreen.V37.Types.ToggleDebitDetails p0

        Evergreen.V35.Types.UpdateDebitDate p0 p1 ->
            Evergreen.V37.Types.UpdateDebitDate p0 p1

        Evergreen.V35.Types.UpdateDebitSecondaryDescription p0 p1 ->
            Evergreen.V37.Types.UpdateDebitSecondaryDescription p0 p1

        Evergreen.V35.Types.UpdateDebitGroup p0 p1 ->
            Evergreen.V37.Types.UpdateDebitGroup p0 p1

        Evergreen.V35.Types.UpdateDebitAmount p0 p1 ->
            Evergreen.V37.Types.UpdateDebitAmount p0 p1

        Evergreen.V35.Types.UpdateGroupName p0 ->
            Evergreen.V37.Types.UpdateGroupName p0

        Evergreen.V35.Types.UpdatePassword p0 ->
            Evergreen.V37.Types.UpdatePassword p0

        Evergreen.V35.Types.UpdateJson p0 ->
            Evergreen.V37.Types.UpdateJson p0

        Evergreen.V35.Types.ViewportChanged p0 p1 ->
            Evergreen.V37.Types.ViewportChanged p0 p1

        Evergreen.V35.Types.ToggleTheme ->
            Evergreen.V37.Types.ToggleTheme

        Evergreen.V35.Types.GroupTransactionsScrolled p0 ->
            Evergreen.V37.Types.GroupTransactionsScrolled p0

        Evergreen.V35.Types.GroupTransactionsViewportChecked p0 ->
            Evergreen.V37.Types.GroupTransactionsViewportChecked p0


migrate_Types_GroupTransactionsCursor : Evergreen.V35.Types.GroupTransactionsCursor -> Evergreen.V37.Types.GroupTransactionsCursor
migrate_Types_GroupTransactionsCursor old =
    old


migrate_Types_TransactionId : Evergreen.V35.Types.TransactionId -> Evergreen.V37.Types.TransactionId
migrate_Types_TransactionId old =
    old
