module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V5.Types
import Evergreen.V6.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V5.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V5.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V5.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V5.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V5.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V5.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V5.Types.FrontendModel -> Evergreen.V6.Types.FrontendModel
migrate_Types_FrontendModel old =
    { showDialog = old.showDialog |> Maybe.map migrate_Types_Dialog
    , user = old.user
    , nameValidity = old.nameValidity |> migrate_Types_NameValidity
    , userGroups =
        old.userGroups
            |> Maybe.map
                (\rec ->
                    { debitors = rec.debitors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    , creditors = rec.creditors |> List.map (\( t1, t2, t3 ) -> ( t1, t2 |> migrate_Types_Group, t3 |> migrate_Types_Amount ))
                    }
                )
    , group = old.group
    , groupValidity = old.groupValidity |> migrate_Types_NameValidity
    , groupTransactions =
        old.groupTransactions
            |> List.map
                (\rec ->
                    { description = rec.description
                    , year = rec.year
                    , month = rec.month
                    , day = rec.day
                    , total = rec.total |> migrate_Types_Amount
                    , share = rec.share |> migrate_Types_Amount
                    }
                )
    , key = old.key
    , windowWidth = 1000
    , windowHeight = 1000
    }


migrate_Types_AddGroupDialogModel : Evergreen.V5.Types.AddGroupDialogModel -> Evergreen.V6.Types.AddGroupDialogModel
migrate_Types_AddGroupDialogModel old =
    { name = old.name
    , nameInvalid = old.nameInvalid
    , members = old.members |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , submitted = old.submitted
    }


migrate_Types_AddPersonDialogModel : Evergreen.V5.Types.AddPersonDialogModel -> Evergreen.V6.Types.AddPersonDialogModel
migrate_Types_AddPersonDialogModel old =
    old


migrate_Types_AddSpendingDialogModel : Evergreen.V5.Types.AddSpendingDialogModel -> Evergreen.V6.Types.AddSpendingDialogModel
migrate_Types_AddSpendingDialogModel old =
    { description = old.description
    , date = old.date
    , dateText = old.dateText
    , datePickerModel = old.datePickerModel
    , total = old.total
    , credits = old.credits |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , debits = old.debits |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> migrate_Types_NameValidity ))
    , submitted = old.submitted
    }


migrate_Types_Amount : Evergreen.V5.Types.Amount a_old -> Evergreen.V6.Types.Amount a_new
migrate_Types_Amount old =
    case old of
        Evergreen.V5.Types.Amount p0 ->
            Evergreen.V6.Types.Amount p0


migrate_Types_Dialog : Evergreen.V5.Types.Dialog -> Evergreen.V6.Types.Dialog
migrate_Types_Dialog old =
    case old of
        Evergreen.V5.Types.AddPersonDialog p0 ->
            Evergreen.V6.Types.AddPersonDialog (p0 |> migrate_Types_AddPersonDialogModel)

        Evergreen.V5.Types.AddGroupDialog p0 ->
            Evergreen.V6.Types.AddGroupDialog (p0 |> migrate_Types_AddGroupDialogModel)

        Evergreen.V5.Types.AddSpendingDialog p0 ->
            Evergreen.V6.Types.AddSpendingDialog (p0 |> migrate_Types_AddSpendingDialogModel)

        Evergreen.V5.Types.PasswordDialog p0 ->
            Evergreen.V6.Types.PasswordDialog (p0 |> migrate_Types_PasswordDialogModel)


migrate_Types_FrontendMsg : Evergreen.V5.Types.FrontendMsg -> Evergreen.V6.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V5.Types.UrlClicked p0 ->
            Evergreen.V6.Types.UrlClicked p0

        Evergreen.V5.Types.UrlChanged p0 ->
            Evergreen.V6.Types.UrlChanged p0

        Evergreen.V5.Types.NoOpFrontendMsg ->
            Evergreen.V6.Types.NoOpFrontendMsg

        Evergreen.V5.Types.ShowAddPersonDialog ->
            Evergreen.V6.Types.ShowAddPersonDialog

        Evergreen.V5.Types.ShowAddGroupDialog ->
            Evergreen.V6.Types.ShowAddGroupDialog

        Evergreen.V5.Types.ShowAddSpendingDialog ->
            Evergreen.V6.Types.ShowAddSpendingDialog

        Evergreen.V5.Types.SetToday p0 ->
            Evergreen.V6.Types.SetToday p0

        Evergreen.V5.Types.Submit ->
            Evergreen.V6.Types.Submit

        Evergreen.V5.Types.Cancel ->
            Evergreen.V6.Types.Cancel

        Evergreen.V5.Types.UpdateName p0 ->
            Evergreen.V6.Types.UpdateName p0

        Evergreen.V5.Types.AddMember p0 ->
            Evergreen.V6.Types.AddMember p0

        Evergreen.V5.Types.UpdateMember p0 p1 ->
            Evergreen.V6.Types.UpdateMember p0 p1

        Evergreen.V5.Types.UpdateShare p0 p1 ->
            Evergreen.V6.Types.UpdateShare p0 p1

        Evergreen.V5.Types.ChangeDatePicker p0 ->
            Evergreen.V6.Types.ChangeDatePicker p0

        Evergreen.V5.Types.UpdateTotal p0 ->
            Evergreen.V6.Types.UpdateTotal p0

        Evergreen.V5.Types.AddCreditor p0 ->
            Evergreen.V6.Types.AddCreditor p0

        Evergreen.V5.Types.UpdateCreditor p0 p1 ->
            Evergreen.V6.Types.UpdateCreditor p0 p1

        Evergreen.V5.Types.UpdateCredit p0 p1 ->
            Evergreen.V6.Types.UpdateCredit p0 p1

        Evergreen.V5.Types.AddDebitor p0 ->
            Evergreen.V6.Types.AddDebitor p0

        Evergreen.V5.Types.UpdateDebitor p0 p1 ->
            Evergreen.V6.Types.UpdateDebitor p0 p1

        Evergreen.V5.Types.UpdateDebit p0 p1 ->
            Evergreen.V6.Types.UpdateDebit p0 p1

        Evergreen.V5.Types.UpdateGroupName p0 ->
            Evergreen.V6.Types.UpdateGroupName p0

        Evergreen.V5.Types.UpdatePassword p0 ->
            Evergreen.V6.Types.UpdatePassword p0


migrate_Types_Group : Evergreen.V5.Types.Group -> Evergreen.V6.Types.Group
migrate_Types_Group old =
    old |> Dict.map (\k -> migrate_Types_Share)


migrate_Types_NameValidity : Evergreen.V5.Types.NameValidity -> Evergreen.V6.Types.NameValidity
migrate_Types_NameValidity old =
    case old of
        Evergreen.V5.Types.Complete ->
            Evergreen.V6.Types.Complete

        Evergreen.V5.Types.Incomplete ->
            Evergreen.V6.Types.Incomplete

        Evergreen.V5.Types.InvalidPrefix ->
            Evergreen.V6.Types.InvalidPrefix


migrate_Types_PasswordDialogModel : Evergreen.V5.Types.PasswordDialogModel -> Evergreen.V6.Types.PasswordDialogModel
migrate_Types_PasswordDialogModel old =
    old


migrate_Types_Share : Evergreen.V5.Types.Share -> Evergreen.V6.Types.Share
migrate_Types_Share old =
    case old of
        Evergreen.V5.Types.Share p0 ->
            Evergreen.V6.Types.Share p0
